let mySprite = sprites.create(img`
    ........................
    ....ffffff..............
    ..ffccccfcf.............
    .ffccccfcccf............
    .fcccffccccf...cc.......
    .ffffcccccccf.cdc.......
    .fccccffffccfcddc.......
    fffffffcccffcddc........
    ffcccc32ccccddc.........
    fccccc32ccccdc..........
    .fcccccccfdccc..........
    ..ffccfffcddc...........
    ...fccfccccc............
    ...fccfffff.............
    ...fccccccf.............
    ....ffffff..............
    .....fff................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
